version: "3"
services:
  fill:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5439:5432/tcp
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql